title:            Manyu's Blog
tagline:          There is a blog at level 0.
description:      The content of this blog is a random function.
#Comment out url when working locally to resolve base urls correctly
#url:              http://your-site.com

# Owner/author information
owner:
  name:           Abhimanyu "Coden" Mongandh Ambalath
  avatar:         bio-photo.jpg
  bio:            "I am here."
  email:          abhi@manyu.in
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  github:         abhimanyuma
  twitter:        abhimanyuma
  facebook:       abhimanyu.m.a
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: All articles
    url: /articles
  - title: Personal
    url: /personal
  - title: Tech
    url: /tech
  - title: Projects
    url: /projects
  - title: About
    url: /about
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]